### PR TITLE
Update github/dericofilho -> github/phpfmt

### PR DESCRIPTION
**Pull request by rogeriopradoj**

### CODE REVIEW

**Comment by ccirello** [comment]
This PR is incomplete. Run build.php

**Comment by ccirello** [comment]
Superceded by 52bf2c80f867537480c9a9a1be5edabc56ee1699

**Comment by rogeriopradoj** [comment]
Alright, thanks for letting me know!

**Comment by ccirello** [comment]
Thanks for the PR

**Pull request closed without merging**
